### ISSUE TITLE
Guide: how to join the DCR Matrix channels

### ISSUE THREAD

**Issue by noahpierau** [xaur/decred-issues#147]
I think we need a Decred specific guide on how to join Matrix / Riot. how to switch to the Decred home server, how to find DCR channels if you are not on the Decred home server. as our user base grows, more and more people will have support questions. let's make the "customer care" process as smooth as possible for them by providing them the quickest way to ask their questions

**Comment by xaur** [comment]
What we have now is:

- https://decred.org/matrix/ that provides some guidance
- https://chat.decred.org/ has Decred's homeserver preconfigured and also serves its own instance of Riot Web

But I agree there's a lot to enhance here. I'll see if I can bump some of my notes.

> let's make the "customer care" process as smooth as possible for them by providing them the quickest way to ask their questions

Agreed but support is a special beast. If this issue is specifically about support, we need to focus on that. Like build a decent entry point at decred.org/support that routes people to #support room.

**Comment by xaur** [comment]
Speaking of support, I expect chat support will not scale to much. We may need to run our own support system that optimizes comms for that specific use case (user accounts, tickets, assignees, enhanced privacy for sensitive stuff, etc). That might need a separate issue.

**Comment by pLabarta** [comment]
Just saw this issue. I added this guide https://dcrcomic.org/guide-enter-the-matrix.html to dcrdocs: https://docs.decred.org/getting-started/joining-matrix-channels/

**Comment by xaur** [comment]
Very nice work @pLabarta! @noahpierau does the new [docs page](https://docs.decred.org/getting-started/joining-matrix-channels/) resolve your initial request?

**Comment by noahpierau** [comment]
issue is resolved by comic + docs page
