### ISSUE TITLE
Make Discord more spam resistant

### ISSUE THREAD

**Issue by xaur** [xaur/decred-issues#16]
Lot's of spam is coming from Discord.

One of the measures suggested was to manually grant users permission to post messages in a special guest room.

**Comment by sambiohazard** [comment]
The problem as described in the title has led to calls for decommissioning/un-bridging of discord. I think a better solution exists.

**The solution**

Discord comes with much better moderation tools than slack as it is designed to host a public community. Here are some of the steps we can take to alleviate the problem.

- First step should be to appoint moderators (volunteers are welcome) who can manually ban and clean up messages. Moderators will also be needed for steps mentioned below. Also it will be great to have a server admin/owner to be appointed who is a regular online member and experienced in this role.

- Second step would be to use basic moderation settings (image below) to curtail members with unverified emails or those who have new accounts. This can cut down the bot attacks significantly in my opinion.

![Basic Moderation Settings](https://i.imgur.com/ryhSyVg.png)

- Third step is to utilize “User Roles” in Discord to curtail what users can do immediately after joining the server. Below are some of the settings that can be disabled by default.

![User Settings 1](https://i.imgur.com/3eboUho.png)

![User Settings 2](https://i.imgur.com/JkPIEQj.png)

Users can also be prevented from joining voice chat if needed.

![User Settings 3](https://i.imgur.com/WZQd2op.png)

- Fourth step is to create a “Verified” user role which will be enabled for an account by a moderator when
  - A user sets a profile pic
  - Asks to be verified by a mod.

This can be done by creating following channels
 - welcome – read only channel instructing people how to enable more functions for themselves, e.g. instruction to check verification email, setting up profile pic and asking for verification in check-post channel
 - check-post – This will be the channel where people can ask for getting verified user role by a moderator. It will be only channel with permission to post or visible to unverified users. It can be rate limited to a post every 2 mins.

With above settings and enough moderators, we can reduce almost all the bots and spam from discord. Many crypto communities are already using similar model to effectively keep their servers free of bots.

**What I can do**
 - I can do all the setup as described above if granted proper permissions or can work with a moderator/admin if they need my help.
 - ~~I am also willing to be one of the moderators to get this plan going.~~ Already Done. Thanks!

**What I need help with**
 - More moderators to join in so that all channels can be monitored and users can be verified all the time across different time zones.
 - A community member who is regularly online to become admin so that moderators can be added/removed and other admin functions be handled.
 - Someone who can test the bridge and other integrations like twitter bot are not broken when enabling theses settings.

Any suggestions on how to proceed and inform current discord users with minimum disruption are welcome. Also, any suggestions on details of what settings to use are welcome.

**Comment by sambiohazard** [comment]
Update: First two steps are now implemented

 - We now have at least 2-3 mods present at a time. This seems good enough for now, might need more mods present if Verified user role is required in future.
 - Upped verification level to Low, which requires user to have a verified email id associated with the discord account, in order post messages. Bridge seems to be working fine, monitoring if anyone reports any problems.

Further steps to increase engagement

 - Going to create a welcome channel with instructions to verify email, basic rules and general description of different channels.
 - Probably will move join messages from general channel to a new channel/maybe disable them/move to check-post channel if verification is implemented. These clutter the discussion if lots of people join at a time.

**Comment by xaur** [comment]
Related [discussion](https://matrix.to/#/!MgQoetFiyjrHAywokv:decred.org/$15463925305155yKrKr:decred.org).

**Comment by sambiohazard** [comment]
So the full setup with User Roles and increased moderation is now in place. If anyone is interested in details of User Roles, see this: https://gist.github.com/sambiohazard/b99a1f6b2c0f942825d21a29a05b6f16

We are now monitoring the situation and verifying people as they ask. As of time of this comment 62 members asked for verification and were verified by moderators. There are ~150-200 members (all roles included) who are online and overall 2000+ members on discord server. Response seems lukewarm but overall reaction seems positive to new setup. People are trickling in for verification.

I have been given target of 1 spam message per week to consider this setup a success. So far we are on track for this week since i became admin/mod for discord (Jan 03, 2018). One slipped thru as verification was not in place by then.

So far 0 spam since activation of verification system (~24 hour).

I hope this works. Thanks for the opportunity to "Make discord great again!" 
I will keep updating this as weeks go by.

**Comment by sambiohazard** [comment]
Fair point, didn't think about it. I will disable that for everyone role. Indeed it might be used more if we dont verify someone as that is the only thing they can do other than reading channels. Thanks!

**Comment by sambiohazard** [comment]
Week 1 Update:
 - There was no spam from a bot for first week of verification system. Additionally we didn't see any trolls either, which is a plus.

 - 85 members asked for verification and were verified. There are 20-30 verified members online on average and 150-180 in total. It was a dull start but we got some activity going as week went by.
 - Total number of members is at 2078.

I will consider this a success for first week. Thanks to all the other mods/admins (Exitus, yasabi & cryptoHaag) and once again Haon and bee for their support!

**Comment by xaur** [comment]
Great news, thank you for the update!

Are all existing users going through manual approval for permission to post? If so, do I read right that of 2078 users <180 asked for it?

- [ ] test

**Comment by xaur** [comment]
Yah it worked, so the tip: instead of striking out completed items you can use checkboxes: `- [ ] item`. This preserves readability of the items.

**Comment by oregonisaac** [comment]
Well done! Excited it's more functional out there now!

**Comment by sambiohazard** [comment]
> Great news, thank you for the update!
> 
> Are all existing users going through manual approval for permission to post? If so, do I read right that of 2078 users <180 asked for it?
> 
> * [ ]  test

No only 85 members asked for verification (close to 100 now), 150-180 are total online (verified + unverified) and 2078 are total members who joined and were not kicked or banned.

**Comment by sambiohazard** [comment]
i can add a request to avoid editing in welcome channel and do an announcement with everyone tag, but there is no setting for disabling editing. will also suggest how to correct without editing. I hope we can find a better bridging s/w.

**Comment by sambiohazard** [comment]
Week 2 Update:
 - There was no spam from a bot for second week of verification system as well. No trolls either.

 - 97(+12) members asked for verification and were verified. There are 20-30 verified members online on average and 150-180 in total. Luke warm response and activity but i guess once more channels are bridged it will improve.

 - Total number of members is at 2087(+9).

Success for second week as well. yasabi was removed as mod, i wasn't told and i do not agree with the reason either. We introduced a new mod in @elian, thanks to him and all the other mods.

**Comment by xaur** [comment]
Any plans for bridging more channels? Roll by one (starting with most important) or bridge all at once? Now or later when more users get verified?

**Comment by sambiohazard** [comment]
Lets watch this for 2 more weeks, which will make it a month of testing for new system. After that i will open an issue here and list channels that would be good to have bridged for increasing engagement. Right now i know at least 4 people who went back to slack/matrix because of lack of channels like proposals, poleteia or writer's room.

**Comment by sambiohazard** [comment]
Week 3 Update:

 - There was no spam from a bot for third week of verification system as well. No trolls either.

 - 115(+18) members asked for verification and were verified since implementation of system. There are 25-30 verified members online on average and 180-200 in total. 

 - Total number of members is at 2127(+40).

 - A group of 20-30 bots joined with similar names, all were stopped in verification channel although they didn't try to post. No complaints of DM spam either.

Success for third week as well.

**Comment by sambiohazard** [comment]
I think we can consider this issue resolved and close it. No spam for almost a month and multiple new channels bridged to discord. Thanks everyone for the work and support

**Comment by xaur** [comment]
Great work @sambiohazard, thank you! Closing.
